// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBdytg0Iz0TEAhiWfNi8Sr5wfQozmBUSP4',
    appId: '1:351203563004:android:8b1fe2950a5ba2db5c0e79',
    messagingSenderId: '351203563004',
    projectId: 'chat-app-e11e4',
    storageBucket: 'chat-app-e11e4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVC9GlPVf3NU1mLraQfOgcizFh0fXV0Xo',
    appId: '1:351203563004:ios:64ebe904be1dc6195c0e79',
    messagingSenderId: '351203563004',
    projectId: 'chat-app-e11e4',
    storageBucket: 'chat-app-e11e4.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMl1a0n0Gq6Q2ULllisUrSykqceF42tys',
    appId: '1:351203563004:web:288cfd0d576724ba5c0e79',
    messagingSenderId: '351203563004',
    projectId: 'chat-app-e11e4',
    authDomain: 'chat-app-e11e4.firebaseapp.com',
    storageBucket: 'chat-app-e11e4.firebasestorage.app',
    measurementId: 'G-M8E20KV2TD',
  );
}
